# -*- coding: utf-8 -*-
"""20220611_金融科技玉山專題_決策樹final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_avPRhZVGbGLTFca2QwCsfiQbEAVINhm
"""

import pickle
import pandas as pd
import numpy as np
import os
from keras.models import Sequential
from keras.layers import Dense

class pred_cat():

    def __init__(self, path = os.getcwd() + "/decisiontree.pkl"):
        with open(path, 'rb') as f:
            self.model = pickle.load(f)
    
    def change_type(self, data):
        if type(data) is list:
            X = pd.DataFrame(data).T
        else:
            X = data
        return X
    
    def extract_var(self, data):
        feat = ['sex', 'age', 'hasOtherComAccount', 'incomeYear', 'totalWealth', 'expInvestment', 'srcCapital', 'quotaCredit', 'category_rule_base', 'credit_info', 'lc_var', 'category_insurance']
        X = data[feat]
        return X

    def get_category(self, X):
        model = self.model
        X = self.change_type(X)
        X = self.extract_var(X)

        pred_cat = model.predict(X)
        res = pred_cat.tolist()
        for i in range(len(res)):
            if res[i] == 0:
                res[i] = '0-10萬'
            elif res[i] ==1:
                res[i] = '10-30萬'
            elif res[i] ==2:
                res[i] = '30-50萬'
            elif res[i] ==3:
                res[i] = '50-100萬'
            else:
                pass

        return res

#取資料測試
import os
path = os.getcwd()+ "/data/data_F2.csv"
example = data = pd.read_csv(path)

classifier = pred_cat()
cat = classifier.get_category(example) #list of 預測額度